language: node_js
node_js:
- '8'
- '10'
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
    tags: true
    repo: bisand/node-red-contrib-tibber-api
    tag: next
